import { defineCollection, z } from 'astro:content';

export const SITE_AUTHOR = 'Alexander Ioffe';

/**
 * Docs. Two kinds of page live here and the difference matters for layout:
 *
 *   - `kind: 'prose'` — ordinary documentation, rendered as one column.
 *   - `kind: 'text'`  — a chapter of Derech Tevunos, Hebrew and English
 *     stacked. Generated by `scripts/build-text-docs.ts`; do not hand-edit
 *     the files under `docs/text/`, they are rebuilt on every `npm run build`.
 *
 * `order` sorts within a `category`; `category` groups in the sidebar.
 */
const docs = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    category: z.string(),
    order: z.number().default(0),
    kind: z.enum(['prose', 'text']).default('prose'),
  }),
});

const blog = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    /** Optional secondary headline. Takes the deck slot; `description` stays SEO/meta. */
    subtitle: z.string().optional(),
    description: z.string(),
    date: z.date(),
    /** When the content actually changed. Sitemap lastmod prefers this over `date`. */
    updated: z.date().optional(),
    author: z.string().default(SITE_AUTHOR),
    /** Social-card image. Never rendered in the page body. */
    image: z.string().optional(),
    tags: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

export const collections = { docs, blog };
