import { defineCollection, z } from 'astro:content';

export const SITE_AUTHOR = 'Alexander Ioffe';

/**
 * Docs. Two kinds of page live here and the difference matters for layout:
 *
 *   - `kind: 'prose'` — ordinary documentation, rendered as one column.
 *   - `kind: 'text'`  — a chapter of Derech Tevunos, Hebrew and English
 *     interleaved verse by verse. Generated by `scripts/build-text-docs.ts`;
 *     do not hand-edit the files under `docs/text/`, they are rebuilt on
 *     every `npm run build`.
 *
 * `order` sorts within a `category`; `category` groups in the sidebar.
 *
 * `paragraphs` is what a `text` page's table of contents is built from: the
 * generator emits one entry per paragraph, `id` being the heading's anchor
 * (`p3-14`) and `label` the editorial label with its inline Hebrew already
 * isolated (`<span lang="he">`), so it is rendered with `set:html`. A generated
 * chapter has no Markdown headings for Astro to collect, which is why the list
 * travels in the frontmatter rather than being read off `headings`.
 */
const docs = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    category: z.string(),
    order: z.number().default(0),
    kind: z.enum(['prose', 'text']).default('prose'),
    paragraphs: z.array(z.object({ id: z.string(), label: z.string() })).optional(),
  }),
});

const blog = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    /** Optional secondary headline. Takes the deck slot; `description` stays SEO/meta. */
    subtitle: z.string().optional(),
    description: z.string(),
    date: z.date(),
    /** When the content actually changed. Sitemap lastmod prefers this over `date`. */
    updated: z.date().optional(),
    author: z.string().default(SITE_AUTHOR),
    /** Social-card image. Never rendered in the page body. */
    image: z.string().optional(),
    tags: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

export const collections = { docs, blog };
