/**
 * Six sugyot encoded as move skeletons — id, target, ch. 9 move, incipit —
 * for one question: do long-reaching moves nest inside other long-reaching
 * moves in ordinary Talmud, or is the Bava Metzia 21b–22b fixture (every rail
 * to one of two roots) the normal shape?
 *
 * Text: William Davidson edition via the Sefaria v3 API (see `texts/`). Unit
 * boundaries follow Steinsaltz's segmentation, split where one segment holds
 * two moves (a question and its answer) and merged where one move runs across
 * segments. Labels are inferred from stock phrases only; nothing here is
 * attested by Ramchal. Where a target was genuinely ambiguous the *shorter*
 * reach was chosen, so the nesting counts below are a floor, not a ceiling.
 *
 * Research artefact only — nothing in `viz/src` imports this.
 */

import type { Sugya, Unit } from "../viz/src/sugya.ts";
import type { Move } from "../viz/src/taxonomy.ts";

// Ch. 9 leaves, abbreviated. Effects are the taxonomy's: D/RM/O/ALT/SP unsettle,
// R/A/DET discharge, C reject, P/V raise, S*/Q* open.
const M = {
  S: { element: "statement", subtype: "firsthand" },
  SE: { element: "statement", subtype: "explanation" },
  SI: { element: "statement", subtype: "inference" },
  SR: { element: "statement", subtype: "reported" },
  Q: { element: "question", subtype: "query" },
  QP: { element: "question", subtype: "principle" },
  A: { element: "answer", subtype: "answer" },
  DET: { element: "answer", subtype: "determination" },
  P: { element: "proof", subtype: "demonstration" },
  V: { element: "proof", subtype: "validation" },
  C: { element: "contradiction", subtype: "direct" },
  O: { element: "contradiction", subtype: "opposition" },
  D: { element: "difficulty", subtype: "objection" },
  RM: { element: "difficulty", subtype: "apparentContradiction" },
  R: { element: "resolution", subtype: "settlement" },
  ALT: { element: "resolution", subtype: "alternative" },
} as const satisfies Record<string, Move>;

type Row = readonly [id: string, move: keyof typeof M, target: string | undefined, he: string, en: string];

const build = (
  meta: Omit<Sugya, "units">,
  rows: readonly Row[],
): Sugya => ({
  ...meta,
  units: rows.map(([id, move, target, he, en]): Unit => ({
    id,
    move: M[move],
    ...(target === undefined ? {} : { target }),
    he,
    en,
    short: en,
    attested: false,
  })),
});

/** Bava Metzia 2a–3a — שנים אוחזין: the opening sugya of the tractate. */
export const bavaMetziaOchazin = build(
  {
    id: "bm-2a-ochazin",
    title: "Two holding a garment",
    tractate: "Bava Metzia",
    folio: "2a-3a",
    discussedAt: "Not discussed in Derech Tevunos",
  },
  [
    ["mishnah", "S", undefined, "שנים אוחזין בטלית… ויחלוקו", "Mishnah: two hold a garment, each says I found it, each says it is all mine"],
    ["q-two-clauses", "D", "mishnah", "למה לי למתנא… ליתני חדא!", "Why teach both 'I found it' and 'it is all mine'?"],
    ["a-chada", "R", "q-two-clauses", "חדא קתני", "It teaches one case: I found it and it is all mine"],
    ["q-metzasiha", "D", "a-chada", "וליתני אני מצאתיה ואנא ידענא דכולה שלי", "Then teach only 'I found it'"],
    ["a-reisiha", "R", "q-metzasiha", "אי תנא אני מצאתיה הוה אמינא ראיתיה", "'Found' alone could mean 'saw'; 'all mine' rules that out"],
    ["q-rabbanai", "D", "a-reisiha", "והא אמר רבנאי ומצאתה דאתאי לידיה משמע", "But Rabbanai: 'found' in Scripture means it came to hand"],
    ["a-lishna", "R", "q-rabbanai", "תנא לישנא דעלמא נקט", "The tanna uses everyday speech, where seeing is called finding"],
    ["q-kula-sheli", "D", "a-reisiha", "וליתני כולה שלי ולא בעי אני מצאתיה", "Then teach only 'all mine'"],
    ["a-mishna-yeseira", "R", "q-kula-sheli", "ממשנה יתירה אשמעינן דראיה לא קני", "The extra clause teaches that seeing does not acquire"],
    ["q-ze-veze", "D", "a-chada", "ומי מצית אמרת חדא קתני? והא זה וזה קתני", "How can it be one case? It says 'this one… and this one' twice"],
    ["a-rav-pappa", "R", "q-two-clauses", "אמר רב פפא: רישא במציאה וסיפא במקח וממכר", "Rav Pappa: the first clause is a find, the second a purchase"],
    ["tzricha", "P", "a-rav-pappa", "וצריכא", "And both are needed: a find alone, or a sale alone, would not teach the other"],
    ["q-zuzei", "D", "a-rav-pappa", "מקח וממכר, ולחזי זוזי ממאן נקט?", "A sale? See whose money the seller took"],
    ["a-zuzei", "R", "q-zuzei", "לא צריכא דנקט מתרוייהו", "He took from both, one willingly, one not, and cannot say which"],
    ["q-ben-nannas", "D", "mishnah", "לימא מתניתין דלא כבן ננס", "Is the mishnah not Ben Nannas, who forbids oaths that make one side swear falsely?"],
    ["a-ben-nannas", "R", "q-ben-nannas", "אפילו תימא בן ננס", "Even Ben Nannas: here both may have lifted it together, so no false oath is certain"],
    ["q-sumchos", "D", "mishnah", "לימא מתניתין דלא כסומכוס", "Is the mishnah not Sumchos, who divides doubtful money without an oath?"],
    ["q-ela-rabbanan", "D", "q-sumchos", "ואלא מאי, רבנן? הא אמרי המוציא מחברו עליו הראיה!", "Then whose — the rabbis? They say the claimant must prove"],
    ["a-hai-mai", "R", "q-ela-rabbanan", "האי מאי? אי אמרת בשלמא רבנן", "No: for the rabbis, both holding it is different from neither holding it"],
    ["sharpen-sumchos", "SE", "q-sumchos", "אלא אי אמרת סומכוס… לא כל שכן!", "But for Sumchos, all the more should they divide without an oath"],
    ["a-sumchos-1", "R", "q-sumchos", "אפילו תימא סומכוס: כי אמר סומכוס שמא ושמא", "Even Sumchos: he spoke of two uncertain claims, not two certain ones"],
    ["q-rabbah-b-huna", "D", "a-sumchos-1", "ולרבה בר רב הונא דאמר אמר סומכוס אפילו ברי וברי", "But Rabbah bar Rav Huna has Sumchos say it even for certain claims"],
    ["a-sumchos-2", "R", "q-sumchos", "אפילו תימא סומכוס: היכא דאיכא דררא דממונא", "Even Sumchos: he spoke where there is a prior monetary link"],
    ["q-kal-vachomer", "D", "a-sumchos-2", "ולאו קל וחומר הוא?", "Is it not a fortiori? Here, with no link, all the more divide without an oath"],
    ["a-sumchos-3", "R", "q-sumchos", "אפילו תימא סומכוס: שבועה זו מדרבנן היא כדרבי יוחנן", "Even Sumchos: this oath is rabbinic, as R. Yoḥanan said, against seizing another's cloak"],
    ["q-r-yose", "D", "mishnah", "לימא מתניתין דלא כרבי יוסי", "Is the mishnah not R. Yose, who leaves disputed money until Elijah comes?"],
    ["q-ela-rabbanan-2", "D", "q-r-yose", "אלא מאי רבנן… הא נמי כשאר דמי!", "Then the rabbis? They too leave the remainder until Elijah"],
    ["a-hai-mai-2", "R", "q-ela-rabbanan-2", "האי מאי? אי אמרת בשלמא רבנן", "No: for the rabbis, there one coin certainly belongs to one party; here both may own it"],
    ["sharpen-yose", "SE", "q-r-yose", "אלא אי אמרת רבי יוסי היא… לא כל שכן!", "But for R. Yose, all the more should it wait for Elijah"],
    ["a-yose-1", "R", "q-r-yose", "אפילו תימא רבי יוסי: התם ודאי איכא רמאי", "Even R. Yose: there a cheat is certain, here perhaps both lifted it"],
    ["a-yose-2", "ALT", "q-r-yose", "אי נמי: התם קניס ליה רבי יוסי לרמאי", "Or: there R. Yose penalises the cheat to make him confess; here there is nothing to confess"],
    ["q-tinach", "D", "a-yose-2", "תינח מציאה, מקח וממכר מאי איכא למימר?", "That works for a find; what of a sale?"],
    ["mechavarta", "V", "a-yose-1", "אלא מחוורתא כדשנין מעיקרא", "Rather, the first answer is the clear one"],
    ["q-chenvani", "D", "a-yose-1", "בין לרבנן ובין לרבי יוסי, התם גבי חנוני על פנקסו", "For rabbis and R. Yose alike: the shopkeeper's ledger — both swear and collect, though a cheat is certain"],
    ["a-chenvani", "R", "q-chenvani", "אמרי: התם היינו טעמא", "There the shopkeeper and the worker each have a claim on the employer alone"],
    ["a-chenvani-2", "SE", "a-chenvani", "ושכיר נמי אמר ליה", "And the worker likewise, so both swear and collect from the employer"],
  ],
);

/** Bava Kamma 2a–3b — אבות ותולדות: the opening sugya of the tractate. */
export const bavaKammaToldos = build(
  {
    id: "bk-2a-toldos",
    title: "Are the derivatives like their primaries?",
    tractate: "Bava Kamma",
    folio: "2a-3b",
    discussedAt: "Not discussed in Derech Tevunos",
  },
  [
    ["mishnah", "S", undefined, "ארבעה אבות נזיקין", "Mishnah: four primary categories of damage"],
    ["inf-toldos", "SI", "mishnah", "מדקתני אבות מכלל דאיכא תולדות", "Since it says primaries, there are derivatives"],
    ["q-kayotze", "QP", "inf-toldos", "תולדותיהן כיוצא בהן או לאו כיוצא בהן?", "Are the derivatives like their primaries or not?"],
    ["shabbos", "SR", "q-kayotze", "גבי שבת תנן… תולדותיהן כיוצא בהן", "For Shabbos: thirty-nine primaries, and derivatives are like them"],
    ["q-diff", "Q", "shabbos", "ומאי איכא בין אב לתולדה?", "Then what distinguishes primary from derivative there?"],
    ["a-diff", "A", "q-diff", "נפקא מינה", "Two primaries together are two liabilities; a primary and its derivative are one"],
    ["q-r-eliezer", "D", "a-diff", "ולרבי אליעזר דמחייב אתולדה במקום אב", "For R. Eliezer, who counts them separately, why call one primary and one derivative?"],
    ["a-r-eliezer", "R", "q-r-eliezer", "הך דהוה במשכן חשיבא", "What was significant in the Tabernacle is called primary"],
    ["tumos", "SR", "q-kayotze", "גבי טומאות תנן… תולדותיהן לאו כיוצא בהן", "For impurity: primaries defile people and vessels, derivatives only food and drink"],
    ["q-here", "Q", "q-kayotze", "הכא מאי?", "And here, in damages?"],
    ["a-rav-pappa", "A", "q-here", "אמר רב פפא: יש מהן כיוצא בהן ויש מהן לאו כיוצא בהן", "Rav Pappa: some are like their primaries and some are not"],
    ["baraisa-shor", "SR", "a-rav-pappa", "תנו רבנן: שלשה אבות נאמרו בשור", "Baraisa: three primaries in the ox — horn, tooth, foot"],
    ["q-keren", "Q", "baraisa-shor", "קרן מנלן?", "Whence horn?"],
    ["a-keren", "A", "q-keren", "דתנו רבנן: כי יגח — אין נגיחה אלא קרן", "'If it gores' — goring is with the horn, as in Zedekiah's iron horns, and 'his firstborn bull… the horns of the wild ox'"],
    ["q-veomer", "Q", "a-keren", "מאי ואומר?", "Why the second verse?"],
    ["a-veomer", "A", "q-veomer", "וכי תימא דברי תורה מדברי קבלה לא ילפינן", "Lest you say Torah is not derived from the Prophets — the second verse is Torah"],
    ["q-gilui", "D", "a-veomer", "והאי מילף הוא?! גילוי מילתא בעלמא הוא", "Is that a derivation? It merely reveals a meaning"],
    ["a-tam-muad", "A", "q-veomer", "אלא מהו דתימא… בתלושה", "Rather: lest you say the tam/muad distinction applies only to a detached horn"],
    ["q-toldah-keren", "Q", "baraisa-shor", "תולדה דקרן מאי היא?", "What is a derivative of horn?"],
    ["a-toldah-keren", "A", "q-toldah-keren", "נגיפה, נשיכה, רביצה ובעיטה", "Pushing, biting, crouching, kicking"],
    ["q-negifa", "D", "a-toldah-keren", "נגיפה נמי כתיב כי יגף!", "Pushing is written too — why is it a derivative?"],
    ["a-negifa", "R", "q-negifa", "האי נגיפה נגיחה היא", "That 'pushing' is goring: the verse opens with one and closes with the other"],
    ["q-adam-behema", "Q", "a-negifa", "מאי שנא גבי אדם דכתיב כי יגח", "Why 'gore' for a person and 'push' for an animal?"],
    ["a-mazla", "A", "q-adam-behema", "אדם דאית ליה מזלא", "A person has fortune, so the ox must gore; an animal does not"],
    ["agav-orchei", "SI", "a-mazla", "ומלתא אגב אורחיה קא משמע לן", "Incidentally: forewarned for people is forewarned for animals, not the reverse"],
    ["q-neshicha", "D", "a-toldah-keren", "נשיכה — תולדה דשן היא!", "Biting is a derivative of tooth!"],
    ["a-neshicha", "R", "q-neshicha", "לא; שן יש הנאה להזיקה", "No: tooth damages for pleasure, biting does not"],
    ["q-revitza", "D", "a-toldah-keren", "רביצה ובעיטה — תולדה דרגל היא!", "Crouching and kicking are derivatives of foot!"],
    ["a-revitza", "R", "q-revitza", "לא; רגל הזיקה מצוי", "No: foot damage is common, these are not"],
    ["q-ahaya", "Q", "a-rav-pappa", "אלא תולדותיהן לאו כיוצא בהן דאמר רב פפא, אהייא?", "Then Rav Pappa's 'some are not like their primaries' — about which?"],
    ["q-ilema-hanei", "D", "q-ahaya", "אילימא אהני", "If about these horn derivatives — they too intend harm and are your property"],
    ["a-shen-regel", "A", "q-ahaya", "אלא תולדה דקרן כקרן, וכי קאמר רב פפא — אשן ורגל", "Rather horn's derivatives are like horn; Rav Pappa meant tooth and foot"],
    ["q-shen-regel-source", "Q", "a-shen-regel", "שן ורגל היכא כתיבי?", "Where are tooth and foot written?"],
    ["a-shen-regel-source", "A", "q-shen-regel-source", "דתניא: ושלח — זה הרגל… ובער — זו השן", "'And he sends' is foot; 'and it consumes' is tooth"],
    ["amar-mar-regel", "D", "a-shen-regel-source", "אמר מר: ושלח זו הרגל… הא לאו הכי במאי מוקמת לה?", "The master said 'sends' is foot — without the proof-verse, what else could it be?"],
    ["q-keren-shen-written", "SE", "amar-mar-regel", "אי קרן — כתיב! אי שן — כתיב!", "Horn is written; tooth is written"],
    ["a-itztrich", "R", "amar-mar-regel", "אצטריך; סלקא דעתך אמינא אידי ואידי אשן", "Needed: one might have read both verses as tooth"],
    ["q-shen-lo-machlya", "Q", "a-itztrich", "והשתא דאוקימנא ארגל, שן דלא מכליא קרנא מנלן?", "Now that one is foot, whence tooth that does not destroy the principal?"],
    ["a-dumya-regel", "A", "q-shen-lo-machlya", "דומיא דרגל", "By likeness to foot"],
    ["amar-mar-shen", "D", "a-shen-regel-source", "אמר מר: ובער זו השן… הא לאו הכי במאי אוקימנא לה?", "The master said 'consumes' is tooth — without the proof-verse, what else?"],
    ["q-keren-regel-written", "SE", "amar-mar-shen", "אי קרן — כתיב! אי רגל — כתיב!", "Horn is written; foot is written"],
    ["a-itztrich-2", "R", "amar-mar-shen", "איצטריך; סלקא דעתך אמינא אידי ואידי ארגל", "Needed: one might have read both as foot"],
    ["q-regel-memeila", "Q", "a-itztrich-2", "והשתא דאוקי אשן, רגל דאזלה ממילא מנלן?", "Now that one is tooth, whence foot that walks of itself?"],
    ["a-dumya-shen", "A", "q-regel-memeila", "דומיא דשן", "By likeness to tooth"],
    ["q-just-veshalach", "D", "a-shen-regel-source", "ולכתוב רחמנא ושלח ולא בעי ובער", "Let it write only 'sends', which implies both foot and tooth"],
    ["a-o-ha", "R", "q-just-veshalach", "אי לאו קרא יתירה הוה אמינא או הא או הא", "Without the extra verse one might take either one, not both"],
    ["q-shkulin", "D", "a-o-ha", "מכדי שקולין הן ויבאו שניהם", "They are equal; let both come — which would you exclude?"],
    ["a-itztrich-3", "R", "q-shkulin", "איצטריך; סלקא דעתך אמינא הני מילי היכי דשלח שלוחי", "Needed: one might limit it to the owner sending the animal"],
    ["q-toldah-shen", "Q", "a-shen-regel", "תולדה דשן מאי היא?", "What is a derivative of tooth? Rubbing against a wall for pleasure, soiling produce for pleasure"],
    ["q-ma-shna-shen", "D", "q-toldah-shen", "מאי שנא שן דיש הנאה להזיקו… הני נמי!", "These too damage for pleasure and are your property — so they are like tooth"],
    ["a-toldah-regel", "A", "q-ahaya", "אלא תולדה דשן כשן, וכי קאמר רב פפא — אתולדה דרגל", "Rather tooth's derivatives are like tooth; Rav Pappa meant foot's"],
    ["q-toldah-regel", "Q", "a-toldah-regel", "תולדה דרגל מאי היא?", "What is a derivative of foot? Damage with its body, hair, load, bridle, bell while walking"],
    ["q-ma-shna-regel", "D", "q-toldah-regel", "מאי שנא רגל דהזיקו מצוי… הני נמי!", "These too are common and your property — so they are like foot"],
    ["a-toldah-bor", "A", "q-ahaya", "אלא תולדה דרגל כרגל, וכי קאמר רב פפא — אתולדה דבור", "Rather foot's derivatives are like foot; Rav Pappa meant the pit's"],
    ["q-toldah-bor", "D", "a-toldah-bor", "תולדה דבור מאי ניהו? אילימא אב עשרה ותולדה תשעה", "What is a derivative of pit? If ten handbreadths is primary and nine derivative — neither is written"],
    ["a-vehames", "R", "q-toldah-bor", "הא לא קשיא; והמת יהיה לו", "'The dead shall be his': ten kills, nine only injures"],
    ["q-sof-sof", "D", "a-vehames", "סוף סוף, זה אב למיתה וזה אב לנזקין!", "Still, one is primary for death and the other primary for injury"],
    ["a-avno", "ALT", "q-toldah-bor", "אלא אאבנו סכינו ומשאו שהניחן ברשות הרבים", "Rather: his stone, knife or load left in the public way"],
    ["q-heichi-dami", "D", "a-avno", "היכי דמי? אי דאפקרינהו… היינו בור", "How so? Abandoned, it is a pit for Rav and Shmuel alike; not abandoned, it is pit or ox"],
    ["q-ma-shna-bor", "D", "a-avno", "מאי שנא בור שכן תחלת עשייתו לנזק… הני נמי!", "These too are made for damage and your property — so they are like pit"],
    ["a-toldah-maveh", "A", "q-ahaya", "אלא תולדה דבור כבור, וכי קאמר רב פפא — אתולדה דמבעה", "Rather pit's derivatives are like pit; Rav Pappa meant mav'eh's"],
    ["q-mai-nihu", "D", "a-toldah-maveh", "מאי ניהו? אי לשמואל… אי לרב", "Which? For Shmuel mav'eh is tooth, already settled; for Rav it is man — what derivatives has man?"],
    ["q-vechi-teima", "D", "q-mai-nihu", "וכי תימא אב ניעור תולדה ישן; והתנן אדם מועד לעולם", "Awake primary, asleep derivative? Man is always forewarned, awake or asleep"],
    ["a-kicho", "ALT", "q-mai-nihu", "אלא אכיחו וניעו", "Rather: his spittle and phlegm"],
    ["q-heichi-dami-2", "D", "a-kicho", "היכי דמי? אי בהדי דאזלי קמזקי — כחו הוה", "In flight it is his force; at rest it is a pit"],
    ["a-toldah-esh", "A", "q-ahaya", "אלא תולדה דמבעה כמבעה, וכי קאמר רב פפא אתולדה דאש", "Rather mav'eh's derivatives are like mav'eh; Rav Pappa meant fire's"],
    ["q-toldah-esh", "D", "a-toldah-esh", "תולדה דאש מאי ניהו? אילימא אבנו סכינו ומשאו שהניחן בראש גגו", "A stone, knife or load on his roof blown down by a common wind — in flight it is fire itself"],
    ["q-ma-shna-esh", "D", "q-toldah-esh", "מאי שנא אש דכח אחר מעורב בהן… הני נמי!", "These too have another force mixed in and are your property — so they are like fire"],
    ["a-toldah-regel-2", "A", "q-ahaya", "אלא תולדה דאש כאש, וכי קאמר רב פפא — אתולדה דרגל", "Rather fire's derivatives are like fire; Rav Pappa meant foot's"],
    ["q-regel-again", "D", "a-toldah-regel-2", "רגל?! הא אוקימנא תולדה דרגל כרגל!", "Foot? We settled that foot's derivatives are like foot!"],
    ["a-tzroros", "R", "q-regel-again", "בחצי נזק צרורות, דהלכתא גמירי לה", "Pebbles — half damage, a received law"],
    ["q-why-regel", "Q", "a-tzroros", "ואמאי קרי לה תולדה דרגל?", "Why call it a derivative of foot?"],
    ["a-aliyah", "A", "q-why-regel", "לשלם מן העלייה", "To pay from the best property"],
    ["q-rava", "D", "a-aliyah", "והא מבעיא בעי רבא", "But Rava asked whether pebbles pay from the body or the best property"],
    ["a-rava-pappa", "R", "q-rava", "לרבא מבעיא ליה, לרב פפא פשיטא ליה", "For Rava it is a question, for Rav Pappa it is settled"],
    ["q-lerava", "Q", "a-rava-pappa", "לרבא דמבעיא ליה, אמאי קרי לה תולדה דרגל?", "For Rava, why call it a derivative of foot?"],
    ["a-lefotra", "A", "q-lerava", "לפוטרה ברשות הרבים", "To exempt it in the public domain"],
  ],
);

/** Kiddushin 2a–3a — האשה נקנית: the language of the mishnah. */
export const kiddushinNikneis = build(
  {
    id: "kid-2a-nikneis",
    title: "A woman is acquired",
    tractate: "Kiddushin",
    folio: "2a-3a",
    discussedAt: "Not discussed in Derech Tevunos",
  },
  [
    ["mishnah", "S", undefined, "האשה נקנית בשלש דרכים", "Mishnah: a woman is acquired in three ways"],
    ["q-nikneis", "D", "mishnah", "מאי שנא הכא דתני האשה נקנית ומאי שנא התם דתני האיש מקדש?", "Why 'acquired' here and 'betroths' in the next chapter?"],
    ["a-kesef", "R", "q-nikneis", "משום דקא בעי למיתני כסף", "Because it wants to teach money"],
    ["q-kesef-source", "Q", "a-kesef", "וכסף מנא לן?", "And whence money?"],
    ["a-kicha", "A", "q-kesef-source", "גמר קיחה קיחה משדה עפרון", "'Taking' from 'taking' in Ephron's field"],
    ["kicha-kinyan", "SE", "a-kicha", "וקיחה איקרי קנין", "And taking is called acquiring: 'the field Abraham acquired'"],
    ["alt-sados", "ALT", "kicha-kinyan", "אי נמי: שדות בכסף יקנו", "Or: 'fields they shall acquire with money'"],
    ["q-there-koneh", "D", "a-kesef", "וניתני התם האיש קונה!", "Then teach 'the man acquires' there too"],
    ["a-lishna", "R", "q-there-koneh", "מעיקרא תני לישנא דאורייתא ולבסוף תני לישנא דרבנן", "First the Torah's word, then the rabbis' — she is forbidden to all like consecrated property"],
    ["q-here-koneh", "D", "a-kesef", "וניתני הכא האיש קונה!", "Then teach 'the man acquires' here"],
    ["a-seifa", "R", "q-here-koneh", "משום דקא בעי למיתנא סיפא וקונה את עצמה", "Because the end clause, 'acquires herself', is about her"],
    ["q-koneh-umakneh", "D", "a-seifa", "וניתני האיש קונה ומקנה!", "Then teach 'the man acquires and releases'"],
    ["a-misas-habaal", "R", "q-koneh-umakneh", "משום דאיכא מיתת הבעל", "The husband's death releases her, and that is not his doing"],
    ["a-baal-korcha", "ALT", "q-here-koneh", "ואי בעית אימא: אי תנא קונה הוה אמינא אפילו בעל כרחה", "Or: 'acquires' might suggest against her will; 'is acquired' means with her consent"],
    ["q-shalosh", "D", "mishnah", "ומאי איריא דתני שלש? ליתני שלשה!", "Why the feminine 'three'?"],
    ["a-derech-fem", "R", "q-shalosh", "משום דקא בעי למיתני דרך, ודרך לשון נקבה הוא", "Because 'way' is feminine: 'the way they shall walk in it'"],
    ["q-zav", "D", "a-derech-fem", "ואלא הא דתניא בשבעה דרכים בודקין את הזב, ניתני שבע!", "But 'seven ways to examine a zav' uses the masculine"],
    ["a-derech-masc", "R", "q-zav", "ואשכחן דרך דאיקרי לשון זכר", "'Way' is also found masculine: 'by one way… by seven ways'"],
    ["q-kashu", "D", "a-derech-masc", "אי הכי, קשו קראי אהדדי! וקשיא נמי מתניתין אהדדי!", "Then the verses contradict, and the mishnayos contradict"],
    ["a-krai", "R", "q-kashu", "קראי אהדדי לא קשיין", "The verses agree: Torah is feminine, war is a man's"],
    ["a-masnisin", "R", "q-kashu", "מתניתין אהדדי לא קשיין", "The mishnayos agree: a woman's matter is feminine, a man's examination masculine"],
    ["q-devarim", "D", "a-derech-fem", "ניתני דברים וניתני שלשה!", "Why 'ways' at all? Say 'things' and 'three' in the masculine"],
    ["a-biah", "R", "q-devarim", "משום דקבעי למיתני ביאה, וביאה איקרי דרך", "Because of intercourse, which Scripture calls a way"],
    ["q-tinach-biah", "D", "a-biah", "הא תינח ביאה, כסף ושטר מאי איכא למימר?", "That fits intercourse; what of money and document?"],
    ["a-mishum-biah", "R", "q-tinach-biah", "משום ביאה", "Because of intercourse"],
    ["q-tarti", "D", "a-mishum-biah", "ותני תרתי אטו חדא?", "Two named for the sake of one?"],
    ["a-tzorech-biah", "R", "q-tarti", "הנך נמי צורך ביאה נינהו", "Those too are for the sake of intercourse"],
    ["a-r-shimon", "R", "q-devarim", "ואי בעית אימא: הא מני — רבי שמעון היא", "Or: it is R. Shimon, for whom 'the way of a man' is to seek a wife"],
    ["q-zav-devarim", "D", "a-r-shimon", "והא דתנן בשבעה דרכים בודקין את הזב, ליתני דברים!", "Then the zav's 'seven ways' should say 'things'"],
    ["a-zav-devarim", "R", "q-zav-devarim", "התם הא קא משמע לן", "There it teaches that the way of overeating brings on the discharge"],
    ["q-esrog", "D", "a-r-shimon", "והא דתנן אתרוג שוה לאילן בשלשה דרכים, ליתני דברים!", "And 'the citron is like a tree in three ways' should say 'things'"],
    ["a-esrog", "R", "q-esrog", "משום דבעינן מתני סיפא ולירק בדרך אחד", "Because the end clause says 'like a vegetable in one way'"],
    ["q-esrog-seifa", "D", "a-esrog", "סיפא נמי ניתני דבר!", "The end clause too should say 'thing'"],
    ["a-esrog-seifa", "R", "q-esrog-seifa", "התם הא קמשמע לן דדרכיה דאתרוג כירק", "There it teaches the citron's way is a vegetable's way"],
    ["q-koy-gittin", "D", "a-r-shimon", "והא דתנן כוי… ניתני דברים! ותו… גיטי נשים…", "And the koy's 'ways', and 'one of the ways divorce and manumission agree' — say 'things'"],
    ["a-plugta", "R", "q-devarim", "אלא: כל היכא דאיכא פלוגתא תני דרכים", "Rather: where there is a dispute it says 'ways', where none, 'things'"],
    ["dayka-nami", "V", "a-plugta", "דיקא נמי דקתני סיפא", "Indeed: the end clause has R. Eliezer say 'like a tree in every thing'"],
  ],
);

/** Gittin 2a–3a — בפני נכתב ובפני נחתם: Rabbah and Rava. */
export const gittinBefanai = build(
  {
    id: "git-2a-befanai",
    title: "Written before me, signed before me",
    tractate: "Gittin",
    folio: "2a-3a",
    discussedAt: "Not discussed in Derech Tevunos",
  },
  [
    ["mishnah", "S", undefined, "המביא גט ממדינת הים צריך שיאמר בפני נכתב ובפני נחתם", "Mishnah: one who brings a bill of divorce from abroad must declare it was written and signed before him"],
    ["q-taama", "Q", "mishnah", "מאי טעמא?", "Why?"],
    ["rabbah", "A", "q-taama", "רבה אמר: לפי שאין בקיאין לשמה", "Rabbah: because abroad they are not versed in writing it for her sake"],
    ["rava", "O", "rabbah", "רבא אמר: לפי שאין עדים מצויין לקיימו", "Rava: because witnesses are not available to ratify it"],
    ["q-beinaihu", "Q", "rava", "מאי בינייהו?", "What is the practical difference?"],
    ["a-beinaihu", "A", "q-beinaihu", "איכא בינייהו דאתיוהו בי תרי", "Two bearers; province to province in the Land; within one province abroad"],
    ["q-rabbah-trei", "D", "rabbah", "ולרבה דאמר לפי שאין בקיאין לשמה — ליבעי תרי!", "For Rabbah, require two witnesses, as for all testimony"],
    ["a-ed-echad", "R", "q-rabbah-trei", "עד אחד נאמן באיסורין", "One witness is believed in matters of prohibition"],
    ["q-ischazek", "D", "a-ed-echad", "אימור דאמרינן עד אחד נאמן באיסורין… אבל הכא דאיתחזק איסורא", "Only where no prohibition is established; here she is an established married woman, a matter of two"],
    ["a-rov", "R", "q-ischazek", "רוב בקיאין הן… והכא משום עיגונא אקילו בה רבנן", "Most are versed; the requirement is rabbinic, and they were lenient lest she be stranded"],
    ["q-kula", "D", "a-rov", "האי קולא הוא?! חומרא הוא!", "Lenient? It is strict: with one witness the husband can protest and invalidate it"],
    ["a-kula", "R", "q-kula", "כיון דאמר מר: בפני כמה נותנו לה?", "Since it is given before two or three, he checks first and will not undo himself"],
    ["q-rava-trei", "D", "rava", "ולרבא דאמר לפי שאין עדים מצויין לקיימו — ליבעי תרי!", "For Rava, require two witnesses, as for ratifying any document"],
    ["a-ed-echad-2", "R", "q-rava-trei", "עד אחד נאמן באיסורין", "One witness is believed in matters of prohibition"],
    ["q-ischazek-2", "D", "a-ed-echad-2", "אימר דאמרינן עד אחד נאמן באיסורין… אבל הכא איתחזק איסורא", "Only where no prohibition is established; here it is"],
    ["a-bedin", "R", "q-ischazek-2", "בדין הוא דבקיום שטרות נמי לא ליבעי", "Ratification itself needs none by right, as Reish Lakish said; the rabbis required it and were lenient here"],
    ["q-kula-2", "D", "a-bedin", "האי קולא הוא?! חומרא הוא!", "Lenient? It is strict"],
    ["a-kula-2", "R", "q-kula-2", "כיון דאמר מר: בפני כמה נותנו לה?", "Since it is given before two or three, he checks first"],
    ["q-rava-not-rabbah", "Q", "rava", "ורבא, מאי טעמא לא אמר כרבה?", "Why does Rava not say as Rabbah?"],
    ["a-mi-katani", "A", "q-rava-not-rabbah", "אמר לך: מי קתני בפני נכתב לשמה?", "The mishnah does not say 'written for her sake'"],
    ["q-verabbah", "D", "a-mi-katani", "ורבה?", "And Rabbah?"],
    ["a-bedin-2", "R", "q-verabbah", "בדין הוא דליתני הכי, אלא דאי מפשת ליה דיבורא אתי למגזייה", "It should have; but a longer formula would be clipped"],
    ["q-hashta", "D", "a-bedin-2", "השתא נמי אתי למגזייה!", "Now too he may clip it"],
    ["a-chada", "R", "q-hashta", "חדא מתלת גאיז, חדא מתרתי לא גאיז", "One of three is clipped; one of two is not"],
    ["q-rabbah-not-rava", "Q", "rabbah", "ורבה, מאי טעמא לא אמר כרבא?", "Why does Rabbah not say as Rava?"],
    ["a-nichtav", "A", "q-rabbah-not-rava", "אם כן ניתני בפני נחתם ותו לא; בפני נכתב למה לי?", "Then 'signed before me' alone would do; 'written' shows the requirement is for her sake"],
    ["q-verava", "D", "a-nichtav", "ורבא?", "And Rava?"],
    ["a-bedin-3", "R", "q-verava", "בדין הוא דליתני הכי, אלא דאם כן אתי לאיחלופי בקיום שטרות דעלמא", "It should have; but it would be confused with ordinary ratification by one witness"],
    ["q-mi-dami", "D", "a-bedin-3", "ורבה: מי דמי?! התם ידעינן הכא בפני", "Rabbah: is it alike? There 'we know', here 'before me'; there a woman is not believed, here she is"],
    ["a-atu", "R", "q-mi-dami", "ורבא אמר לך: אטו הכא כי אמרי ידעינן מי לא מהימני?!", "Rava: here too 'we know' would be believed, so the confusion stands"],
    ["q-rabbah-tanna", "D", "rabbah", "ולרבה דאמר לפי שאין בקיאין לשמה, מאן האי תנא", "For Rabbah, which tanna requires both writing and signing for her sake?"],
  ],
);

/** Berakhot 2a–3a — מאימתי: the opening sugya of the Talmud. */
export const berakhotMeeimasai = build(
  {
    id: "ber-2a-meeimasai",
    title: "From when is the evening Shema recited",
    tractate: "Berakhot",
    folio: "2a-3a",
    discussedAt: "Not discussed in Derech Tevunos",
  },
  [
    ["mishnah", "S", undefined, "מאימתי קורין את שמע בערבין? משעה שהכהנים נכנסים לאכול בתרומתן", "Mishnah: from when the priests enter to eat their teruma"],
    ["q-heicha-kai", "D", "mishnah", "תנא היכא קאי דקתני מאימתי?", "On what does the tanna stand, that he asks 'from when'?"],
    ["q-arvis-risha", "D", "mishnah", "ותו: מאי שנא דתני בערבית ברישא?", "And why teach evening first?"],
    ["a-akra", "R", "q-heicha-kai", "תנא אקרא קאי דכתיב בשכבך ובקומך", "He stands on the verse 'when you lie down and when you rise'"],
    ["a-briyaso", "ALT", "q-arvis-risha", "ואי בעית אימא: יליף מברייתו של עולם", "Or: from the creation — 'there was evening and there was morning'"],
    ["q-ihachi-seifa", "D", "a-briyaso", "אי הכי, סיפא דקתני בשחר מברך שתים לפניה", "Then the later mishnah on blessings should also put evening first"],
    ["a-pasach", "R", "q-ihachi-seifa", "תנא פתח בערבית והדר תני בשחרית", "He opened with evening, then treated morning fully before returning"],
    ["amar-mar-kohanim", "D", "mishnah", "אמר מר: משעה שהכהנים… לתני משעת צאת הכוכבים!", "The master said 'when the priests enter' — say 'when the stars come out'"],
    ["a-agav", "R", "amar-mar-kohanim", "מלתא אגב אורחיה קמשמע לן", "It teaches in passing that priests eat at nightfall and that atonement does not hold them back"],
    ["kidtanya", "V", "a-agav", "כדתניא: ובא השמש וטהר", "As taught: 'the sun sets and he is clean' — sunset holds him back, atonement does not"],
    ["q-mimai", "D", "kidtanya", "וממאי דהאי ובא השמש ביאת השמש… דילמא ביאת אורו הוא", "Whence that 'the sun sets' is sunset and 'clean' is the day? Perhaps it is sunrise and the man is clean"],
    ["a-rabbah-b-shila", "R", "q-mimai", "אמר רבה בר רב שילא: אם כן לימא קרא ויטהר", "Rabbah bar Rav Shila: then it would say 'and he shall be clean'; 'and it is clean' is the day"],
    ["maarava", "QP", "q-mimai", "במערבא הא דרבה בר רב שילא לא שמיע להו, ובעו לה מיבעיא", "In the West they had not heard this and asked it as a question"],
    ["a-pashtu", "DET", "maarava", "והדר פשטו לה מברייתא", "And resolved it from the baraisa's 'the sign is the stars'"],
    ["amar-mar-rominhu", "RM", "mishnah", "אמר מר: משעה שהכהנים… ורמינהו: משהעני נכנס לאכול פתו במלח", "The master said 'when the priests enter' — but a baraisa: from when the poor man enters to eat his bread"],
    ["q-seifa-risha", "SI", "amar-mar-rominhu", "סיפא ודאי פליגא אמתניתין. רישא מי לימא פליגי אמתניתין?", "Its end clause surely differs; does its first clause?"],
    ["a-chad-shiura", "R", "amar-mar-rominhu", "לא, עני וכהן חד שיעורא הוא", "No: the poor man and the priest are one time"],
    ["rominhu-2", "SR", "a-chad-shiura", "ורמינהו: משעה שבני אדם נכנסין לאכול פתן בערבי שבתות דברי רבי מאיר", "A baraisa: R. Meir, when people enter to eat on Sabbath eves; the sages, when priests may eat teruma, the sign being the stars"],
    ["q-veomer", "Q", "rominhu-2", "מאי ואומר?", "Why the second verse?"],
    ["a-veomer", "A", "q-veomer", "וכי תימא מכי ערבא שמשא ליליא הוא", "Lest you say night begins at sunset and they merely worked late"],
    ["q-chachamim-rm", "RM", "a-chad-shiura", "ואי אמרת עני וכהן חד שעורא הוא, חכמים היינו רבי מאיר?", "If poor man and priest are one time, and poor man and people are one time, the sages are R. Meir"],
    ["shma-mina", "SI", "q-chachamim-rm", "אלא שמע מינה עני שעורא לחוד וכהן שעורא לחוד", "So the poor man's time and the priest's differ"],
    ["a-lo", "R", "q-chachamim-rm", "לא, עני וכהן חד שעורא הוא, ועני ובני אדם לאו חד שעורא הוא", "No: poor man and priest are one; poor man and people are not"],
    ["rominhu-3", "RM", "a-lo", "ועני וכהן חד שעורא הוא? ורמינהו", "One time? A baraisa: R. Eliezer, R. Yehoshua, R. Meir, R. Yehuda, R. Ḥanina, R. Aḥai each give a time"],
    ["q-chanina-yehoshua", "SE", "rominhu-3", "ואי אמרת עני וכהן חד שעורא הוא, רבי חנינא היינו רבי יהושע!", "If they were one, R. Ḥanina would be R. Yehoshua"],
    ["shma-mina-2", "C", "a-lo", "אלא לאו שמע מינה שעורא דעני לחוד ושעורא דכהן לחוד, שמע מינה", "So the poor man's time and the priest's differ — conclude so"],
    ["q-hei-meuchar", "Q", "shma-mina-2", "הי מינייהו מאוחר?", "Which is later?"],
    ["a-ani-meuchar", "DET", "q-hei-meuchar", "מסתברא דעני מאוחר", "The poor man's, else R. Ḥanina would be R. Eliezer"],
    ["amar-mar-yehuda", "SR", "rominhu-3", "אמר מר: אמר ליה רבי יהודה: והלא כהנים מבעוד יום הם טובלים!", "The master said: R. Yehuda replied, priests immerse while it is still day"],
    ["q-shapir", "D", "amar-mar-yehuda", "שפיר קאמר ליה רבי יהודה לרבי מאיר?", "Did R. Yehuda answer R. Meir well?"],
    ["a-rm", "R", "q-shapir", "ורבי מאיר הכי קאמר ליה", "R. Meir meant R. Yose's twilight, which is a blink"],
    ["q-rm-adrm", "RM", "rominhu-3", "קשיא דרבי מאיר אדרבי מאיר!", "R. Meir contradicts R. Meir"],
    ["a-trei-tannai", "R", "q-rm-adrm", "תרי תנאי אליבא דרבי מאיר", "Two tannaim report R. Meir"],
    ["q-re-adre", "RM", "rominhu-3", "קשיא דרבי אליעזר אדרבי אליעזר!", "R. Eliezer contradicts R. Eliezer"],
    ["a-trei-tannai-2", "R", "q-re-adre", "תרי תנאי אליבא דרבי אליעזר, ואיבעית אימא רישא לאו רבי אליעזר היא", "Two tannaim report R. Eliezer; or the mishnah's first clause is not his"],
    ["clause-ashmura", "SR", "mishnah", "עד סוף האשמורה", "'Until the end of the first watch'"],
    ["q-mai-kasavar", "D", "clause-ashmura", "מאי קסבר רבי אליעזר?", "What does R. Eliezer hold? Three watches — say four hours; four — say three"],
    ["a-leolam", "R", "q-mai-kasavar", "לעולם קסבר שלש משמרות הוי הלילה", "Three watches; he teaches there are watches in heaven as on earth"],
    ["siman", "SR", "a-leolam", "וסימן לדבר", "The signs: a donkey brays, dogs howl, a child nurses and a wife talks with her husband"],
    ["q-mai-chashiv", "D", "siman", "מאי קא חשיב רבי אליעזר?", "Does he count beginnings or ends? The first beginning and the last end need no sign"],
    ["a-sof-rishona", "R", "q-mai-chashiv", "אלא חשיב סוף משמרה ראשונה", "He counts the end of the first, the start of the last, and the middle of the middle"],
  ],
);

/** Pesachim 2a–3a — מאי אור: the opening sugya of the tractate. */
export const pesachimOr = build(
  {
    id: "pes-2a-or",
    title: "What is 'or'?",
    tractate: "Pesachim",
    folio: "2a-3a",
    discussedAt: "Not discussed in Derech Tevunos",
  },
  [
    ["mishnah", "S", undefined, "אור לארבעה עשר בודקין את החמץ לאור הנר", "Mishnah: on the 'or' of the fourteenth one searches for leaven by lamplight"],
    ["q-mai-or", "Q", "mishnah", "מאי אור?", "What is 'or'?"],
    ["rav-huna", "A", "q-mai-or", "רב הונא אמר: נגהי", "Rav Huna: daybreak"],
    ["rav-yehuda", "O", "rav-huna", "ורב יהודה אמר: לילי", "Rav Yehuda: night"],
    ["ka-salka", "SE", "rav-yehuda", "קא סלקא דעתך דמאן דאמר נגהי — נגהי ממש", "The assumption: daybreak means actual day and night means actual night"],
    ["m1", "D", "rav-yehuda", "מיתיבי: הבקר אור — אלמא אור יממא הוא!", "'The morning was light' — so 'or' is day"],
    ["a1", "R", "m1", "מי כתיב האור בקר?", "It says 'the morning lit up', not 'the light was morning'"],
    ["m2", "D", "rav-yehuda", "מיתיבי: וכאור בקר יזרח שמש", "'As the light of morning the sun rises' — so 'or' is day"],
    ["a2", "R", "m2", "מי כתיב אור בקר?", "It says 'like the light of morning' — the world to come"],
    ["m3", "D", "rav-yehuda", "מיתיבי: ויקרא אלהים לאור יום", "'God called the light day' — so 'or' is day"],
    ["a3", "R", "m3", "הכי קאמר: למאיר ובא קראו יום", "It means: the brightening he called day"],
    ["q3", "D", "a3", "אלא מעתה, ולחשך קרא לילה — למחשיך ובא קרא לילה?!", "Then 'the darkness he called night' would be dusk — but until the stars it is day"],
    ["a3b", "R", "m3", "אלא הכי קאמר: קרייה רחמנא לנהורא ופקדיה אמצותא דיממא", "Rather: He summoned the light and charged it with the day's duties"],
    ["m4", "D", "rav-huna", "מיתיבי: הללוהו כל כוכבי אור — אלמא אור אורתא הוא", "'Praise Him, all stars of light' — so 'or' is night"],
    ["a4", "R", "m4", "הכי קאמר: הללוהו כל כוכבים המאירים", "It means: all shining stars"],
    ["q4", "D", "a4", "אלא מעתה, כוכבים המאירים הוא דבעו שבוחי", "Then only shining stars praise? 'Praise Him, all His hosts'"],
    ["a4b", "R", "q4", "אלא הא קא משמע לן דאור דכוכבים נמי אור הוא", "It teaches that starlight is light — for one who vows off light"],
    ["m5", "D", "rav-yehuda", "מיתיבי: לאור יקום רוצח… ובלילה יהי כגנב", "'At light the murderer rises… at night he is as a thief' — so 'or' is day"],
    ["a5", "R", "m5", "התם הכי קאמר", "There: if it is clear as light he is a murderer; if doubtful as night, a thief"],
    ["m6", "D", "rav-yehuda", "מיתיבי: יקו לאור ואין", "'Let it hope for light and have none' — so 'or' is day"],
    ["a6", "R", "m6", "התם מילט הוא דקא לייט ליה איוב למזליה", "There Job curses his fortune"],
    ["m7", "D", "rav-yehuda", "מיתיבי: ולילה אור בעדני", "'Night is light about me' — so 'or' is day"],
    ["a7", "R", "m7", "התם הכי קאמר דוד", "There David speaks of this world and the next"],
    ["m8", "D", "rav-huna", "מיתיבי, רבי יהודה אומר: בודקין אור ארבעה עשר ובארבעה עשר שחרית", "R. Yehuda: search on the 'or' of the fourteenth and on the fourteenth morning — so 'or' is night. Conclude so"],
    ["m9", "D", "rav-huna", "מיתיבי: מאימתי ארבעה עשר אסור בעשיית מלאכה?", "R. Eliezer b. Yaakov: from the 'or'; R. Yehuda: from sunrise"],
    ["m9-baraisa", "SR", "m9", "אמר ליה ראב״י לרבי יהודה: וכי היכן מצינו יום שמקצתו אסור", "Their exchange: where is a day part forbidden and part permitted? The day itself proves it, for leaven"],
    ["m9-inference", "SE", "m9", "מדקאמר רבי יהודה משעת הנץ החמה, אלמא אור דקאמר ראב״י — אורתא הוא!", "Since R. Yehuda says sunrise, R. Eliezer's 'or' is night"],
    ["a9", "R", "m9", "לא, מאי אור — עמוד השחר", "No: 'or' is dawn"],
    ["q9", "D", "a9", "אי הכי… נימא איהו לנפשיה: הא איכא לילה", "Then R. Eliezer's own night is a part-permitted day"],
    ["a9b", "R", "q9", "הכי קאמר: בשלמא לדידי אשכחנא דקא פלגי רבנן בין יממא לליליא", "He meant: the rabbis divide day from night, not a day within itself"],
    ["q9c", "D", "a9b", "שפיר קאמר ליה רבי יהודה לרבי אליעזר?", "Did R. Yehuda's leaven answer hold?"],
    ["a9c", "R", "q9c", "הכי קאמר ליה רבי אליעזר: אמינא לך אנא מלאכה דרבנן", "R. Eliezer: I speak of rabbinic labour, you answer with Torah leaven"],
    ["q9d", "Q", "a9c", "ואידך?", "And R. Yehuda?"],
    ["a9d", "A", "q9d", "שעות דרבנן", "The hours are rabbinic"],
    ["q9e", "Q", "a9d", "ואידך?", "And R. Eliezer?"],
    ["a9e", "A", "q9e", "הרחקה הוא דעבוד רבנן לדאורייתא", "A rabbinic fence around Torah law"],
    ["m10", "D", "rav-huna", "מיתיבי: אין משיאין משואות… לאור עבורו", "Beacons are lit on the 'or' of the intercalated day — so 'or' is night. Conclude so"],
    ["m11", "D", "rav-huna", "מיתיבי: היה עומד כל הלילה ומקריב… לאורה טעון קידוש", "One who offers all night must wash at 'orah' — so 'or' is night"],
    ["a11", "R", "m11", "אורה שאני", "'Orah' is different"],
    ["m12", "D", "rav-huna", "מיתיבי מר זוטרא: המפלת אור לשמונים ואחד", "Mar Zutra: miscarrying on the 'or' of the eighty-first — Beis Hillel's reply shows 'or' is night. Conclude so"],
    ["m13", "D", "rav-huna", "מיתיבי: יכול יהא נאכל אור לשלישי", "'It might be eaten on the or of the third day' — so 'or' is night. Conclude so"],
    ["m14", "D", "rav-huna", "תא שמע: אור של יום הכפורים מתפלל שבע ומתודה", "On the 'or' of Yom Kippur one prays seven and confesses — so 'or' is night. Conclude so"],
    ["m15", "D", "rav-huna", "תא שמע דתני דבי שמואל: לילי ארבעה עשר בודקין את החמץ", "Shmuel's school: on the night of the fourteenth one searches — so 'or' is night"],
    ["ela", "C", "ka-salka", "אלא: בין רב הונא ובין רב יהודה דכולי עלמא אור אורתא הוא", "Rather: both agree 'or' is night; each used his own town's word"],
    ["q-tanna", "Q", "mishnah", "ותנא דידן מאי טעמא לא קתני לילי?", "Why does our mishnah not say 'night'?"],
    ["a-lishna", "A", "q-tanna", "לישנא מעליא הוא דנקט", "It chose refined speech, as R. Yehoshua b. Levi taught"],
  ],
);

export const RESEARCH_SUGYOT: readonly Sugya[] = [
  bavaMetziaOchazin,
  bavaKammaToldos,
  kiddushinNikneis,
  gittinBefanai,
  berakhotMeeimasai,
  pesachimOr,
];
